export const INS_URL: string = 'https://instagram.com'
export const FB_URL: string = 'https://facebook.com'
export const THREADS_URL: string = 'https://instagram.com'
export const MYIP_URL: string = 'https://myip.com'
export const SOCIAL_MEDIA_DOWNLOADER_API: string = 'http://localhost:3001/api'