channel:
    profile:
        min_follower: 50000
        timeout: 10000
    friendships:
        batchSize: 1
        timeBetweenBatch: 10
    posts:
        get_detail: false
    reels:
        get_detail: false
download:
    batchSize: 1